language: node_js
node_js:
  - "node"
before_install:
  # Required to avoid libstdc++ errors when running "extended" hugo
  - wget -q -O libstdc++6 http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.10_amd64.deb
  - sudo dpkg --force-all -i libstdc++6

script: npm test
